# Generated by Django 5.2.3 on 2025-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(unique=True, verbose_name=75095),
        ),
    ]
