# Generated by Django 5.2.3 on 2025-06-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_alter_link_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(default=25630, unique=True),
        ),
    ]
