# Generated by Django 5.2.3 on 2025-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_alter_link_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(default=22362, unique=True),
        ),
    ]
