# Generated by Django 5.2.3 on 2025-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_alter_link_file_alter_link_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="title",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(default=35088, unique=True),
        ),
    ]
